textures=['Dirt','Bricks','MoltenRock','FrostGround','DarkDirt','Black','BlueBricks','DarkFrostGround','sky1','sky2']
edgeTextures=['GrassAlt','Grass','GrayBricks','Ice1','BlueBricks','RedBricks']
particleSources=['Smoke','Fire']
sprites=['SnowMan','Bridge','BlankSignLeft1','BlankSignRight1','ThisWaySignLeft1','Tree1','Grass1','HangingVines2','HangingVines1','FinSignLeft1','CastleWindow1','Tut3Sign','CastleDoor1','HStones','ThisWaySignRight1','FinSignRight1','Tree2','YellowFlare']
rversions=['0.2.4']
