textures={
'ArcticsBlue1': {'file': 'ArcticsBlue1_417.jpg'},
'ArcticsBlue2': {'file': 'ArcticsBlue2_418.jpg'},
'ArcticsBlue3': {'file': 'ArcticsBlue3_419.jpg'},
'ArcticsRed1': {'file': 'ArcticsRed1_420.jpg'},
'ArcticsRed2': {'file': 'ArcticsRed2_421.jpg'},
'ArcticsRed3': {'file': 'ArcticsRed3_422.jpg'},
'Asphalt1': {'file': 'Asphalt1_197.jpg'},
'Asphalt2': {'file': 'Asphalt2_198.jpg'},
'Black': {'file': 'Black.jpg'},
'BlackSea': {'file': 'BlackSea_174.jpg'},
'Blue1InRainbows': {'file': 'Blue1InRainbows_465.png'},
'Blue2InRainbows': {'file': 'Blue2InRainbows_470.png'},
'BlueBlue': {'file': 'BlueBlue_173.jpg'},
'BlueBricks': {'file': 'BlueBricks.jpg'},
'BlueDiag': {'file': 'BlueDiag_214.png'},
'BlueViolet': {'file': 'BlueViolet_172.jpg'},
'BlurBlocks1': {'file': 'BlurBlocks1_270.jpg'},
'Bricks': {'file': 'Bricks.jpg'},
'Bricks2': {'file': 'Bricks2_271.jpg'},
'BubbleDark': {'file': 'BubbleDark_371.jpg'},
'BubbleLight': {'file': 'BubbleLight_370.jpg'},
'ComicClouds': {'file': 'ComicClouds_213.jpg'},
'DarkDirt': {'file': 'DarkDirt.jpg'},
'DarkFrostGround': {'file': 'DarkFrostGround.jpg'},
'DarkWood2': {'file': 'DarkWood2_159.jpg'},
'DegradGreen': {'file': 'DegradGreen_169.jpg'},
'DegradOrange': {'file': 'DegradOrange_168.jpg'},
'Dirt': {'file': 'Dirt.jpg'},
'Dirt_fg': {'file': 'Dirt_fg_243.jpg'},
'Flesh01': {'file': 'Flesh01_410.jpg'},
'FrostGround': {'file': 'FrostGround.jpg'},
'Grass1': {'file': 'Grass1_210.png'},
'Grass2': {'file': 'Grass2_211.jpg'},
'GreenInRainbows': {'file': 'GreenInRainbows_467.png'},
'GroundGravel': {'file': 'GroundGravel_272.jpg'},
'KRWBlueRockDark': {'file': 'KRWBlueRockDark_253.jpg'},
'KRWBlueRockVeryDark': {'file': 'KRWBlueRockVeryDark_254.jpg'},
'KRWNightSky': {'file': 'KRWNightSky_255.jpg'},
'KRWNightSkyMoon': {'file': 'KRWNightSkyMoon_256.jpg'},
'KRWNightSkyNoMoon': {'file': 'KRWNightSkyNoMoon_257.jpg'},
'Lava': {'file': 'Lava_372.jpg'},
'Marble': {'file': 'Marble_645.png'},
'MarbleTilePurple': {'file': 'MarbleTilePurple_178.jpg'},
'MarbleTilePurple_light': {'file': 'MarbleTilePurple_179.jpg'},
'Metal': {'file': 'Metal_190.jpg'},
'Metal2': {'file': 'Metal2_191.jpg'},
'Metal3': {'file': 'Metal3_192.jpg'},
'Metaltile': {'file': 'Metaltile_646.png'},
'MoltenRock': {'file': 'MoltenRock.jpg'},
'Moon': {'file': 'Moon_223.png'},
'Notebook': {'file': 'Notebook_534.png'},
'Orange1InRainbows': {'file': 'Orange1InRainbows_466.png'},
'Orange2InRainbows': {'file': 'Orange2InRainbows_468.png'},
'Peau': {'file': 'Peau_416.png'},
'Red1': {'file': 'Red1_215.jpg'},
'RedInRainbows': {'file': 'RedInRainbows_469.png'},
'Rust': {'file': 'Rust_193.jpg'},
'Sand': {'file': 'Sand_310.jpg'},
'SandDark': {'file': 'SandDark_311.jpg'},
'Sky2Drift': {'file': 'Sky2Drift.jpg'},
'Sky3': {'file': 'Sky3_297.jpg'},
'SolidOrange': {'file': 'SolidOrange_170.jpg'},
'Space': {'file': 'Space_194.jpg'},
'TiZeta': {'file': 'TiZeta_278.jpg'},
'TilesBlue': {'file': 'TilesBlue_180.jpg'},
'TilesGreen': {'file': 'TilesGreen_181.jpg'},
'TilesOrange': {'file': 'TilesOrange_182.jpg'},
'TilesRed': {'file': 'TilesRed_183.jpg'},
'TilesTeal': {'file': 'TilesTeal_184.jpg'},
'TilesYellow': {'file': 'TilesYellow_185.jpg'},
'TransparentBlue1': {'file': 'TransparentBlue1_269.png'},
'Ubuntu': {'file': 'Ubuntu_171.jpg'},
'Wallpaper1': {'file': 'Wallpaper1_195.jpg'},
'Wallpaper2': {'file': 'Wallpaper2_196.jpg'},
'Water1': {'file': 'Water1_186.jpg'},
'Water2': {'file': 'Water2_187.jpg'},
'Wood2': {'file': 'Wood2_158.jpg'},
'Wood3': {'file': 'Wood3_296.png'},
'Yellow': {'file': 'Yellow_177.jpg'},
'YellowInRainbows': {'file': 'YellowInRainbows_464.png'},
'autumn': {'file': 'autumn_481.jpg'},
'blackwhite': {'file': 'blackwhite_231.jpg'},
'block': {'file': 'block_649.png'},
'brickwall': {'file': 'brickwall_642.png'},
'chessy_dark': {'file': 'chessy_dark_200.jpg'},
'chessy_light': {'file': 'chessy_light_199.jpg'},
'chessybackground': {'file': 'chessybackground_242.jpg'},
'chessymiddle': {'file': 'chessymiddle_241.jpg'},
'chessytoodark': {'file': 'chessytoodark_207.jpg'},
'crystal_tex': {'file': 'crystal_tex_487.png'},
'darkgrey': {'file': 'darkgrey_295.png'},
'darkwood': {'file': 'darkwood_157.jpg'},
'fuego': {'file': 'fuego_189.jpg'},
'glass1': {'file': 'glass1_364.png'},
'glass_blue': {'file': 'glass_blue_473.png'},
'glass_green': {'file': 'glass_green_475.png'},
'glass_red': {'file': 'glass_red_474.png'},
'greek': {'file': 'greek_486.png'},
'helltiles': {'file': 'helltiles_176.jpg'},
'hochhaus': {'file': 'hochhaus_298.jpg'},
'hochhaus2': {'file': 'hochhaus2_299.jpg'},
'hochhaus3': {'file': 'hochhaus3_300.jpg'},
'hochhaus4': {'file': 'hochhaus4_301.jpg'},
'invisible': {'file': 'invisible_676.png'},
'lightgrey': {'file': 'lightgrey_293.png'},
'loupechene': {'file': 'loupechene_277.jpg'},
'mediumgrey': {'file': 'mediumgrey_294.png'},
'moresand': {'file': 'moresand_484.png'},
'moresand2': {'file': 'moresand2_485.png'},
'mud': {'file': 'mud_497.jpg'},
'pop_background': {'file': 'pop_background.jpg'},
'pop_bricks': {'file': 'pop_bricks.jpg'},
'pop_bricks_top': {'file': 'pop_bricks_top.jpg'},
'shadow1': {'file': 'shadow1_423.png'},
'shadow2': {'file': 'shadow2_424.png'},
'skin': {'file': 'skin_537.jpg'},
'sky1': {'file': 'Sky1.jpg'},
'sky2': {'file': 'Sky2.jpg'},
'snow': {'file': 'snow_175.jpg'},
'snow_sprite': {'file': 'snow_sprite_377.png'},
'stone_white': {'file': 'stone_white_357.jpg'},
'street': {'file': 'street.jpg'},
'technics': {'file': 'technics_362.jpg'},
'technics_dark': {'file': 'technics_dark_363.jpg'},
'tiles': {'file': 'tiles_510.png'},
'vloup': {'file': 'vloup_279.jpg'},
'white': {'file': 'white_472.jpg'},
'wood': {'file': 'wood.jpg'}}
edgeTextures={
'Bloodeffect': {'file': 'Bloodeffect_407.png'},
'BlueBricks': {'file': 'EdgeBlueBricks1.jpg'},
'EarthVines': {'file': 'EarthVines.png'},
'EdgeCSite1': {'file': 'EdgeCSite1_209.png'},
'EdgeGrass2': {'file': 'EdgeGrass1.png'},
'Glow': {'file': 'Glow_654.png'},
'Grass': {'file': 'EdgeGrass1.png'},
'GrassAlt': {'file': 'EdgeGrassAlt1.png'},
'GrassAlt2': {'file': 'EdgeGrassAlt1.png'},
'GrayBricks': {'file': 'EdgeGrayBricks1.jpg'},
'Green_Liquid': {'file': 'Green_Liquid_526.png'},
'Ice1': {'file': 'EdgeIce1.png'},
'KRWBlueRockEdge': {'file': 'KRWBlueRockEdge_252.png'},
'RedBricks': {'file': 'EdgeRedBricks1.jpg'},
'bluen': {'file': 'bluen_365.png'},
'darken': {'file': 'darken_288.png'},
'dirt_fx': {'file': 'dirt_fx_471.png'},
'lighten': {'file': 'lighten_369.png'},
'stone_fx': {'file': 'stone_fx_483.png'},
'street': {'file': 'street_245.png'},
'street2': {'file': 'street2_404.png'}}
particleSources={
'Smoke': {'file': 'Smoke1.png'},
'Fire': {'file': 'Fire1.png'}}
sprites={
'BlankSignLeft1': {'file': 'BlankSignLeft1.png','width': '1.5','height': '1.5','centerX': '0.75','centerY': '0.1'},
'BlankSignRight1': {'file': 'BlankSignRight1.png','width': '1.5','height': '1.5','centerX': '0.75','centerY': '0.1'},
'Bridge': {'file': 'Bridge.png','width': '4','height': '1.65','centerX': '2','centerY': '1.65'},
'CastleDoor1': {'file': 'CastleDoor1.png','width': '4','height': '4','centerX': '2','centerY': '0.02'},
'CastleWindow1': {'file': 'CastleWindow1.png','width': '2','height': '3','centerX': '1','centerY': '0.02'},
'DangerSign': {'file': 'DangerSign_524.png','width': '1.5','height': '1.5','centerX': '0.75','centerY': '0.75'},
'Daulphin': {'file': 'Daulphin_166.png','width': '3','height': '3','centerX': '1.5','centerY': '0.2'},
'Daulphin2': {'file': 'Daulphin2_162.png','width': '3','height': '3','centerX': '1.5','centerY': '0.2'},
'Earth': {'file': 'Earth_164.png','width': '3','height': '3','centerX': '1.5','centerY': '0.2'},
'FinSignLeft1': {'file': 'FinSignLeft1.png','width': '1.5','height': '1.5','centerX': '0.75','centerY': '0.1'},
'FinSignRight1': {'file': 'FinSignRight1.png','width': '1.5','height': '1.5','centerX': '0.75','centerY': '0.1'},
'Flower': {'file': 'Flower00.png','width': '1','height': '1','centerX': '0.5'},
'Grass1': {'file': 'Grass1.png','width': '0.5','height': '0.5','centerX': '0.25','centerY': '0.15'},
'Grass3': {'file': 'Grass3_527.png','width': '0.7','height': '0.7','centerX': '0.35','centerY': '0.35'},
'HStones': {'file': 'HStones.png','width': '0.8','height': '2','centerX': '0.4','centerY': '0.03'},
'HangingVines1': {'file': 'HangingVines1.png','width': '3.0','height': '4.0','centerX': '1.5','centerY': '3.6'},
'HangingVines2': {'file': 'HangingVines2.png','width': '3.0','height': '4.0','centerX': '1.5','centerY': '3.6'},
'HellHead': {'file': 'HellHead_167.png','width': '3','height': '3','centerX': '1.5','centerY': '0.2'},
'KeyBrake': {'file': 'KeyBrake_500.png','width': '1','height': '1','centerX': '0.5','centerY': '0.5'},
'KeyDrive': {'file': 'KeyDrive_499.png','width': '1','height': '1','centerX': '0.5','centerY': '0.5'},
'KeyLeft': {'file': 'KeyLeft_501.png','width': '1','height': '1','centerX': '0.5','centerY': '0.5'},
'KeyRight': {'file': 'KeyRight_502.png','width': '1','height': '1','centerX': '0.5','centerY': '0.5'},
'MetallicaWrecker': {'file': 'MetallicaWrecker_273_00.png'},
'MultiBaloons': {'file': 'MultiBaloons_163.png','width': '3','height': '3','centerX': '1.5','centerY': '0.2'},
'Nenufart': {'file': 'Nenufart_165.png','width': '3','height': '3','centerX': '1.5','centerY': '0.2'},
'Pig': {'file': 'Pig_653.png'},
'ScriptWarning': {'file': 'ScriptWarning_309.png','width': '3.5','height': '3.5','centerX': '1.7','centerY': '1.0'},
'SnowMan': {'file': 'SnowMan.png','width': '1.5','height': '2.0','centerX': '0.75','centerY': '0.3'},
'Star': {'file': 'Star00.png','width': '0.5','height': '0.5','centerX': '0.25','centerY': '0.25'},
'Strawberry': {'file': 'Strawberry00.png','width': '1','height': '1','centerX': '0.5'},
'Sun': {'file': 'Sun_161.png','width': '3','height': '3','centerX': '1.5','centerY': '0.2'},
'Teleport': {'file': 'Teleport_505_00.png','width': '4.0','height': '4.2','centerX': '2.1','centerY': '1.5'},
'TheX': {'file': 'TheX_488_00.png'},
'ThisWaySignLeft1': {'file': 'ThisWaySignLeft1.png','width': '1.5','height': '1.5','centerX': '0.75','centerY': '0.1'},
'ThisWaySignRight1': {'file': 'ThisWaySignRight1.png','width': '1.5','height': '1.5','centerX': '0.75','centerY': '0.1'},
'Tree1': {'file': 'Tree1.png','width': '5','height': '6','centerX': '2.5','centerY': '0.2'},
'Tree2': {'file': 'Tree2.png','width': '5','height': '6','centerX': '2.5','centerY': '0.2'},
'Tut3Sign': {'file': 'Tut3Sign.png','width': '3','height': '3','centerX': '1.5','centerY': '0.2'},
'TuxFly': {'file': 'TuxFly_160.png','width': '3','height': '3','centerX': '1.5','centerY': '0.2'},
'Wrecker': {'file': 'Wrecker00.png','width': '1','height': '1'},
'YellowFlare': {'file': 'YellowFlare.png','width': '2','height': '2','centerX': '1','centerY': '1','blendmode': 'add'},
'alien': {'file': 'alien_238_00.png','width': '1.0','height': '1.0','centerX': '0.5','centerY': '0.5'},
'beerleft': {'file': 'beerleft_222.png','width': '0.5','height': '0.6','centerX': '0.2','centerY': '0.3'},
'bird': {'file': 'bird_ani_00.png','width': '1','height': '1','centerX': '0.5','centerY': '0'},
'birdright': {'file': 'bird_ani_right_00.png','width': '1','height': '1','centerX': '0.5','centerY': '0'},
'checkball': {'file': 'checkball_235_00.png','width': '1','height': '1'},
'cloud': {'file': 'cloud_523.png','width': '3.0','height': '3.0','centerX': '1.5','centerY': '1.5'},
'cog2': {'file': 'cog2_240_00.png','width': '1','height': '1','centerX': '0.45'},
'cow': {'file': 'cow_379.png','width': '2','height': '2','centerX': '1.0','centerY': '0.8'},
'crossthingy': {'file': 'crossthingy_536.png','width': '0.9','height': '0.9','centerX': '0.45','centerY': '0.45'},
'deathstar': {'file': 'deathstar_234_00.png','width': '0.95','height': '0.95','centerX': '0.49'},
'dock': {'file': 'docks_Stange.png','width': '1','height': '3','centerX': '0.5','centerY': '0.25'},
'drummertux': {'file': 'drummertux_582.png'},
'evilfish': {'file': 'evilfish_225_00.png','width': '1.3','height': '1.3','centerX': '0.65','centerY': '0.65'},
'eyesindark': {'file': 'eyesindark_00.png','width': '1','height': '1','centerX': '1.50','centerY': '1'},
'heart1': {'file': 'heart1_361_00.png'},
'home01': {'file': 'home01.png','width': '8','height': '6','centerX': '3','centerY': '0'},
'laser': {'file': 'laser_239_00.png','width': '0.8','height': '0.8','centerX': '0.4','centerY': '0.4'},
'mototux': {'file': 'mototux_581.png'},
'mushrooms': {'file': 'mushrooms_525.png','width': '0.6','height': '0.6','centerX': '0.3','centerY': '0.3'},
'palmgrass': {'file': 'palmgrass_204.png','width': '1.5','height': '1.5','centerX': '0.75','centerY': '0.5'},
'palmtree': {'file': 'palmtree_201.png','width': '5.7','height': '5.7','centerX': '2.85','centerY': '0.5'},
'palmtree2': {'file': 'palmtree2_202.png','width': '5.7','height': '5.7','centerX': '2.85','centerY': '0.5'},
'panel': {'file': 'panel_230.png','width': '2.6','height': '2.6','centerX': '1.3','centerY': '0.8'},
'ring': {'file': 'ring_228_00.png','width': '0.8','height': '0.8','centerX': '0.4','centerY': '0.4'},
'rocket': {'file': 'rocket_516.png'},
'rocktux': {'file': 'rocktux_580.png'},
'smiley': {'file': 'smiley_480_00.png'},
'spacetux': {'file': 'spacetux_588.png'},
'sunflower': {'file': 'sunflower_205_00.png','width': '2.1','height': '2.1','centerX': '1.05'},
'tomate': {'file': 'tomate_00.png','width': '2.25','height': '2.5','centerY': '0'},
'totem1': {'file': 'totem1_203.png','width': '2.7','height': '2.7','centerX': '1.35','centerY': '0.5'},
'totem2': {'file': 'totem2_206.png','width': '2.7','height': '2.7','centerX': '1.35','centerY': '0.5'},
'tree': {'file': 'tree_381.png','width': '7','height': '7','centerX': '3.5','centerY': '1.2'},
'tux': {'file': 'tux_589.png'},
'zombie_fat': {'file': 'zombie_animiert_00.png','width': '2.25','height': '2.5','centerY': '0'}}
rversions=['0.2.0','0.2.1','0.2.2','0.2.3','0.2.4','0.2.5','0.2.6','0.2.7','0.3.0','0.3.1','0.3.2','0.3.3','0.3.4','0.4.0','0.4.1','0.4.2','0.5.0']
musics=['menu1','rideALong','batcave','blockolando','madeirastew','SpeedItUp']
